version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./client
    ports:
      - 5173:5173
    env_file:
      - ./client/.env

    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  api:
    build: ./server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    secrets:
      - sms-service-account-key

    develop:
      watch:
        - path: ./server/requirements.txt
          action: rebuild
        - path: ./server
          target: /app
          action: sync

secrets:
  sms-service-account-key:
    file: ./server/sms-service-account-key.json
